version: '3'

services:
  app:
    # Зображення, що використовуємо (буде збудоване з Dockerfile)
    build: .
    # Порт, на якому буде відкрито додаток у контейнері
    ports:
      - '3000:3000'
    # Робоча директорія у контейнері
    working_dir: /ReactApp/client
    # Запускаємо додаток в режимі фону
    stdin_open: true
    tty: true
